USE Clube;

CREATE TABLE LogPermissao (
    IDLogPermissao INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDPermissao INT NOT NULL,
    NivelPermissao INT NOT NULL,
    Descricao VARCHAR(100) NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogUsuario (
    IDLogUsuario INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDUsuario INT NOT NULL,
    IDPermissao INT,
    Nome VARCHAR(255) NOT NULL,
    CPF VARCHAR(25) NOT NULL,
    DataNasc DATE NOT NULL,
    DataCadastro DATETIME,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogEndereco (
    IDLogEndereco INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDEndereco INT NOT NULL,
    CEP VARCHAR(50) NOT NULL,
    Numero VARCHAR(50) NOT NULL,
    Complemento VARCHAR(50),
    IDUsuario INT NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogTelefone (
    IDLogTelefone INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDTelefone INT NOT NULL,
    CodigoPais VARCHAR(50) NOT NULL,
    DDD VARCHAR(50) NOT NULL,
    Numero VARCHAR(50) NOT NULL,
    IDUsuario INT NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogQuadra (
    IDLogQuadra INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDQuadra INT NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogReservaQuadra (
    IDLogReservaQuadra INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDReservaQuadra INT NOT NULL,
    DataHoraInicio DATETIME NOT NULL,
    DataHoraFim DATETIME NOT NULL,
    IDUsuario INT NOT NULL,
    IDQuadra INT NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogChurrasqueira (
    IDLogChurrasqueira INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDChurrasqueira INT NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Capacidade INT NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LogReservaChurrasqueira (
    IDLogReservaChurrasqueira INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDReservaChurrasqueira INT NOT NULL,
    DataReserva DATE NOT NULL,
    IDUsuario INT NOT NULL,
    IDChurrasqueira INT NOT NULL,
    Acao VARCHAR(100),
    DataAcao DATETIME DEFAULT CURRENT_TIMESTAMP
);
