-- Permissao
DELIMITER //
CREATE TRIGGER proibirDeletePermissao
    BEFORE DELETE ON Permissao
    FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'VOCE NAO PODE DELETAR UMA PERMISSAO';
END;
//
DELIMITER //

DELIMITER //
CREATE TRIGGER proibirAumentarPermissao
    AFTER UPDATE ON Permissao
    FOR EACH ROW
BEGIN
    IF old.NivelPermissao < new.NivelPermissao THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'VOCE NAO PODE AUMENTAR O NIVEL DE UMA PERMISSAO';
    END IF;
END;
//
DELIMITER //

-- Reservas
DELIMITER //
CREATE TRIGGER proibirUpdateReservaChurrasqueira
    BEFORE UPDATE ON ReservaChurrasqueira
    FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'VOCE NAO PODE MODIFICAR UMA RESERVA DA CHURRASQUEIRA';
END;
//
DELIMITER //

DELIMITER //
CREATE TRIGGER proibirUpdateReservaQuadra
    BEFORE UPDATE ON ReservaQuadra
    FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'VOCE NAO PODE MODIFICAR UMA RESERVA DA QUADRA';
END;
//
DELIMITER //
